name: Deploy to EC2

on:
  push:
    branches:
      - main  # Replace with your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
        chmod 600 private_key.pem
        scp -i private_key.pem -r ./MY-URL/* ec2-user@13.51.79.56:/var/www/html
        rm private_key.pem  


