name: Deploy to EC2

on:
  push:
    branches:
      - main  # Change this to your default branch if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files to EC2
      run: |
        scp -i ${{ secrets.EC2_SSH_KEY }} -r ./MY-URL/* ec2-user@YOUR_EC2_IP:/var/www/html
      env:
        EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

