name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy files to EC2
        run: scp -i /Users/mac/Downloads/GA.pem  -r ./MY-URL ec2-user@13.51.79.56:/home/ec2-user/MY-URLL

